/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_ForkNativeUtil */

#ifndef _Included_com_jni_ForkNativeUtil
#define _Included_com_jni_ForkNativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_ForkNativeUtil
 * Method:    forke
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_ForkNativeUtil_forke
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
