/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myapplication_jni_JniUtil */

#ifndef _Included_com_myapplication_jni_JniUtil
#define _Included_com_myapplication_jni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myapplication_jni_JniUtil
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myapplication_jni_JniUtil_getCLanguageString
  (JNIEnv *, jobject);

/*
 * Class:     com_myapplication_jni_JniUtil
 * Method:    forke
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_myapplication_jni_JniUtil_forke
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
